#!/usr/bin/env sh
echo "😈Starting pre-commit hook..."
. "$(dirname -- "$0")/_/husky.sh"
echo "😈Running npm run lint..."
npm run lint
echo "😈Ready to commit. Note: unstaged files were format/linted but NOT automatically staged."
echo "😈Pre-commit hook completed."